" Script made by p4p1, Last modified: Mon, 20 March 2017
" This script is made to automate vim!
" It set tabs colorscheme and much more
"
" miscs :
set nocompatible

" Plugins :
filetype plugin on

" Color and tabs :
colorscheme quantum
syntax on
set nu
set relativenumber
set colorcolumn=80
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set cursorline
set ruler
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<
set list
" epitech:
" set tabstop=8
" set shiftwidth=2
" inoremap <Tab> <Space><Space>

" backup files dirrectory
set backupdir=./.backup,.,/tmp

" unmap the arrow keys!
no <down> <Nop>
no <left> <Nop>
no <up> <Nop>
no <right> <Nop>
ino <down> <Nop>
ino <left> <Nop>
ino <up> <Nop>
ino <right> <Nop>
vno <down> <Nop>
vno <left> <Nop>
vno <up> <Nop>
vno <right> <Nop>

" line number for inside of insert mode or not
autocmd InsertEnter * :set nornu nolist
autocmd InsertLeave * :set relativenumber list

" General commands :
inoremap <Space><Space> <Esc>/TODO:<Enter>
inoremap ;i <Esc>:set noexpandtab<Enter>A<Tab><Esc>:set expandtab<Enter>A
map <F3> :!pwd&&ls<Enter>
map <F2> :!cat %<Enter>

" C file commands :
autocmd bufnewfile *main.c so ~/.vim/c_main_template.txt
autocmd FileType c inoremap ;h <Esc>:1<Enter>i/*<Enter>Made by: Leo Smith<Enter><Enter>Description: <++><Enter><Backspace>/<Enter><Enter>
autocmd FileType c map <F5> :!gcc % ; ./a.out

" h file commands :
autocmd bufnewfile *.h so ~/.vim/h_template.txt

" Python file commands :
autocmd FileType python inoremap ;h <Esc>:1<Enter>i#!/usr/bin/env python<Enter># -*- coding: utf-8 -*-<Enter># Script made by Leo Smith<Enter># <++>
autocmd FileType python map <F5> :!python %<Enter>

" html file commands :
autocmd bufnewfile *.html so ~/.vim/html_template.txt

" arduino file commands :
autocmd FileType arduino inoremap ;h <Esc>:1<Enter>i/*<Enter>Made by: Leo Smith<Enter><Enter>Description: <++><Enter><Backspace>/<Enter><Enter>
autocmd bufnewfile *.ino so ~/.vim/arduino_template.txt

" All text file commands:
inoremap ;b <Esc>:1i#!/bin/bash<Enter># Made by: Leo Smith<Enter># Description: <++><Enter>
autocmd BufNewFile * :write
