# Webdump A program made by papi to view raw http requests
# look at my other github projects i really try and make really cool things ;)

CC=gcc
FLAGS=-std=c99 -Wall -Wextra -pedantic
EXEC=webdump

all:
	$(CC) source/*.c $(FLAGS) -o $(EXEC)

mrproper:
	rm -rf $(EXEC) a.out
